application: cosmic-hack
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /bower_components/(.*)
  static_dir: static/bower_components/\1

- url: /js/(.*)
  static_dir: static/js/\1

- url: /css/(.*)
  static_dir: static/css/\1

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /.*
  script: main.py
