application: cosmic-hack
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /bower_components
  static_dir: static/bower_components

- url: /img
  static_dir: static/img

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /.*
  script: main.py
